# FROM zenika/alpine-maven

# ADD . /root
# WORKDIR /root
# RUN apk --update add make && make dep && make package
# EXPOSE 8080

# CMD make run

FROM maven as build
WORKDIR /workspace/app

COPY . .
RUN mvn package --batch-mode

ARG JAR_FILE=target/*.jar
RUN cp ${JAR_FILE} target/app.jar


FROM amazoncorretto:8 as runtime
#RUN apk --update add fontconfig ttf-dejavu
#RUN addgroup -S demo && adduser -S demo -G demo
#VOLUME /tmp
#USER demo
#WORKDIR /home/demo
EXPOSE 8080
COPY --from=build /workspace/app/target/app.jar ./
ENTRYPOINT ["java","-jar","app.jar"]
